dist: xenial
language: c++
compiler: gcc
before_script:
- sudo apt-get install libboost-test-dev python3-pip -y
- pip3 install setuptools
- pip3 install wheel
- pip3 install conan
- conan install .
script:
  - gcc --version
  - g++ --version
  - cmake --version
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexandrbashkirev:$BINTRAY_API_KEY "https://api.bintray.com/content/alexandrbashkirev/otus_cpp/homeworks/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"